
################################################################################
##
##  This file is part of the Poseidon Kernel, and is made available under
##  the terms of the GNU General Public License version 2.
##
##  Copyright (C) 2020 - The Poseidon Authors
##
################################################################################

ldir	:= $(GET_LOCAL_DIR)

include \
	$(ldir)pic/Makefile \
